version: 0.2.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: u+KuVfwNaVSx3MHSnyjvIAn25rTxUF9HxQs6F7VOG1OlLYtDT7+19f4zskbiXCP2
  skip_symbols: true
- provider: GitHub
  tag: UltraMapper v$(appveyor_build_version)
  release: UltraMapper v$(appveyor_build_version)
  auth_token:
    secure: xdVPCgGLq4ImYFV39Kc4CSd2+bR+HtfN1Iu+NFMYirkeYz4rCboJV+uxiraKjzsO1E7UZelFAmHNXoKRA9IAFEpErerm+/nTjVMtD8AWMyE=
  artifact: /.*\.nupkg/
