version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true
build:
  publish_nuget: true
  verbosity: minimal
only_commits:
  message: /build/
deploy:
- provider: NuGet
  api_key:
    secure: u+KuVfwNaVSx3MHSnyjvIAn25rTxUF9HxQs6F7VOG1OlLYtDT7+19f4zskbiXCP2
  skip_symbols: true
